import express from "express";
import cors from "cors";
import multer from "multer";
import Replicate from "replicate";
import fs from "node:fs/promises";

const app = express();

app.use(cors());

app.use(
  express.json({
    limit: "10mb"
  })
);

const upload = multer({
  dest: "/tmp/",
  limits: {
    fileSize: 100 * 1024 * 1024
  }
});

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
  useFileOutput: false
});

const DEMUCS_MODEL =
  "cjwbw/demucs:25a173108cff36ef9f80f854c162d01df9e6528be175794b81158fa03836d953";

const WHISPER_MODEL =
  "openai/whisper:8099696689d249cf8b122d833c36ac3f75505c666a395ca40ef26f68e7d3d16e";

/*
|--------------------------------------------------------------------------
| Health Check
|--------------------------------------------------------------------------
*/

app.get("/", (req, res) => {
  res.json({
    success: true,
    message: "Sarvesh Karaoke API is running"
  });
});

/*
|--------------------------------------------------------------------------
| Create Karaoke
|--------------------------------------------------------------------------
|
| Input:
| multipart/form-data
| file = audio file
|
| Output:
| karaokeUrl = instrumental
| vocalsUrl = isolated vocals
|
*/

app.post(
  "/api/karaoke/create",
  upload.single("file"),
  async (req, res) => {
    let uploadedPath = null;

    try {
      if (!req.file) {
        return res.status(400).json({
          success: false,
          message: "No audio file uploaded."
        });
      }

      uploadedPath = req.file.path;

      console.log(
        `Creating karaoke for: ${req.file.originalname}`
      );

      const audioBuffer =
        await fs.readFile(uploadedPath);

      const output = await replicate.run(
        DEMUCS_MODEL,
        {
          input: {
            audio: audioBuffer,
            stem: "vocals",
            model_name: "htdemucs",
            shifts: 1,
            overlap: 0.25,
            clip_mode: "rescale",
            mp3_bitrate: 320,
            float32: false,
            output_format: "mp3"
          }
        }
      );

      console.log("Demucs completed.");

      if (!output?.other) {
        throw new Error(
          "Instrumental track was not returned."
        );
      }

      return res.json({
        success: true,

        originalFileName:
          req.file.originalname,

        karaokeUrl:
          output.other,

        vocalsUrl:
          output.vocals ?? ""
      });
    } catch (error) {
      console.error(
        "Karaoke error:",
        error
      );

      return res.status(500).json({
        success: false,
        message:
          "Unable to create karaoke.",
        error:
          error?.message ??
          "Unknown server error"
      });
    } finally {
      if (uploadedPath) {
        try {
          await fs.unlink(
            uploadedPath
          );
        } catch (_) {}
      }
    }
  }
);

/*
|--------------------------------------------------------------------------
| Generate Lyrics
|--------------------------------------------------------------------------
|
| Input JSON:
|
| {
|   "vocalsUrl": "https://..."
| }
|
| Uses the isolated vocals generated by Demucs.
|
*/

app.post(
  "/api/lyrics/generate",
  async (req, res) => {
    try {
      const {
        vocalsUrl
      } = req.body;

      if (
        !vocalsUrl ||
        typeof vocalsUrl !== "string"
      ) {
        return res.status(400).json({
          success: false,
          message:
            "vocalsUrl is required."
        });
      }

      console.log(
        "Generating lyrics..."
      );

      const output =
        await replicate.run(
          WHISPER_MODEL,
          {
            input: {
              audio: vocalsUrl,

              language: "auto",

              translate: false,

              temperature: 0,

              transcription:
                "plain text",

              condition_on_previous_text:
                true,

              suppress_tokens:
                "-1",

              logprob_threshold:
                -1,

              no_speech_threshold:
                0.6,

              compression_ratio_threshold:
                2.4,

              temperature_increment_on_fallback:
                0.2
            }
          }
        );

      console.log(
        "Lyrics generated."
      );

      const segments =
        Array.isArray(output?.segments)
          ? output.segments
              .filter(
                (segment) =>
                  segment.text &&
                  segment.text
                    .trim()
                    .length > 0
              )
              .map(
                (segment) => ({
                  start:
                    Number(
                      segment.start
                    ) || 0,

                  end:
                    Number(
                      segment.end
                    ) || 0,

                  text:
                    segment.text.trim()
                })
              )
          : [];

      return res.json({
        success: true,

        language:
          output?.detected_language ??
          "",

        transcription:
          output?.transcription ??
          "",

        segments
      });
    } catch (error) {
      console.error(
        "Lyrics error:",
        error
      );

      return res.status(500).json({
        success: false,

        message:
          "Unable to generate lyrics.",

        error:
          error?.message ??
          "Unknown server error"
      });
    }
  }
);

/*
|--------------------------------------------------------------------------
| 404
|--------------------------------------------------------------------------
*/

app.use((req, res) => {
  res.status(404).json({
    success: false,
    message: "Endpoint not found."
  });
});

/*
|--------------------------------------------------------------------------
| Start Server
|--------------------------------------------------------------------------
*/

const port =
  process.env.PORT || 10000;

app.listen(
  port,
  "0.0.0.0",
  () => {
    console.log(
      `Server running on port ${port}`
    );
  }
);
